version: '3'

services:
  app:
    container_name: uozone-backend-container
    restart: always
    build: .
    ports:
      - '80:8080'
    links:
      - db
  db:
    container_name: uozone-postgres-container
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=uozonedb
    ports:
      - '5432:5432'
    volumes:
      - uozone-data:/data/db
volumes:
  uozone-data:
    driver: local